### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by starenka** [erroneousboat/slack-term#116]
is it possible? or at least can we have hooks to exec a shell cmd on events?

**Comment by stlk** [comment]
There's a PR that does this #107

**Comment by erroneousboat** [comment]
Ok, the following issue arose when implementing this feature. When enabling desktop notifications for slack-term it will notify you whenever. That means you'll get desktop notifications also when you've focused the terminal. This can be a problem, when you don't want desktop notifications when you're already looking at slack-term. Next to that, I'm not able to gather from within slack-term, whether the user focused the application or not.

I considered implementing the option of not notifying a user when a message arrives in the selected channel. But that would mean if you lose focus of the window and you receive messages on that channel, you will miss that message because no notification was triggered.

So, you can check out the functionality in the following branch: https://github.com/erroneousboat/slack-term/tree/v0.3.3-notify And I would like to know if the implementation is something that is sufficient for people that want desktop notifications, considering the problem described above.
