### ISSUE TITLE
start a kickstarter

### ISSUE THREAD

**Issue by pomke** [erroneousboat/slack-term#130]
Enough people hate running a full slack client that we'll all throw money at you to make this one better. Seriously.

**Comment by erroneousboat** [comment]
I appreciate the sentiment, however my intention for this project is not to make a feature complete alternative to the official slack client. It's cool that people want to use slack-term as an alternative, but I started this project because I wanted to send and receive message from the terminal to slack, at the time this is/was also possible using other alternatives: weechat or using similar programs to slack-term. I never set out to make a "better" slack-client.
