### ISSUE TITLE
Sort users by presence

### ISSUE THREAD

**Issue by j127** [erroneousboat/slack-term#163]
Thanks for writing the program and making it available. A useful feature addition would be to sort users by presence, because Slack doesn't do that any more (or display "who's online" at all at the moment).

(I'm not sure if the presence API is broken now too, because slack-term is showing users as online who are offline in the Slack app.)

**Comment by erroneousboat** [comment]
Hi, thanks for the kind words. At the moment the users are sorting in buckets (channels, groups, mpim, im). I'll have a look how such a feature would be implemented, however I don't want to complicate things further with ordering. This in part because there are a lot of different preferences. E.g.: order by newest message, alphabetical order,  etc.

**Comment by erroneousboat** [comment]
Let's keep the discussion on #176
