### ISSUE TITLE
Hide channels and private messages

### ISSUE THREAD

**Issue by patleeman** [erroneousboat/slack-term#34]
It doesn't seem like there is a way to archive or leave a direct message or group message.  It would be great if there was a hot key + confirmation to remove a channel from the sidebar list.

**Comment by erroneousboat** [comment]
I would recommend unsubscribing yourself from channels from the web application in order to get them removed from your list. I'm considering this as a action that would not happen that often as such, I won't be implementing this in the foreseeable future as I'm not trying to implement a 1-on-1 implementation of all Slack features.
