### ISSUE TITLE
panic runtime error

### ISSUE THREAD

**Issue by kalbasit** [erroneousboat/slack-term#58]
Getting random panics while typing, mostly when using backspace:

```
panic: runtime error: slice bounds out of range 
goroutine 19 [running]:
github.com/erroneousboat/slack-term/vendor/github.com/nsf/termbox-go.PollEvent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/kalbasit/code/profiles/opensource/src/github.com/erroneousboat/slack-term/vendor/github.com/nsf/termbox-go/api.go:330 +0x44f
github.com/erroneousboat/slack-term/handlers.eventHandler.func1(0xc420433600)
	/home/kalbasit/code/profiles/opensource/src/github.com/erroneousboat/slack-term/handlers/event.go:50 +0x30
created by github.com/erroneousboat/slack-term/handlers.eventHandler
	/home/kalbasit/code/profiles/opensource/src/github.com/erroneousboat/slack-term/handlers/event.go:52 +0x3f
```

**Comment by erroneousboat** [comment]
Just to be sure, you are using version 0.2.2?

`slack-term -h`

**Comment by kalbasit** [comment]
@erroneousboat that's correct.

**Comment by erroneousboat** [comment]
Ok, I'm trying to exclude things here, because I'm not able to trigger it myself. Are you also able to trigger it when using the binary? I'm asking this, because from the stacktrace it seems you've installed it by `go get`. It could be happening because of a local version of termbox, but I'm not sure.

I've also made some changes to the code that might help, you can try it out by checking out the branch [v02.3-termbox_events](https://github.com/erroneousboat/slack-term/tree/v0.2.3-termbox_events) and see if you're able to trigger it there.

**Comment by kalbasit** [comment]
@erroneousboat my apologies for not being clear, had a busy week. I did build it myself, but I did so on the branch for https://github.com/erroneousboat/slack-term/pull/57 which in turn uses nlopes/slack at https://github.com/nlopes/slack/pull/176. Can you try the branch from my PR and update slack's branch as well. I'll give your branch a shot.

**Comment by erroneousboat** [comment]
No problem at all, we all do this in our free time :) I'll try what you suggested and see if I'm able to trigger it. Thanks!

**Comment by erroneousboat** [comment]
With version v0.2.3 I'm still able to trigger it when scrolling in de editbox

**Comment by cshirley** [comment]
This fixed in my pull request

**Comment by erroneousboat** [comment]
@cshirley unfortunately, this is not the same issue as in your pull request

**Comment by erroneousboat** [comment]
Closing this issue for now, it doesn't seem to be happening anymore. Will re-open it when it does.
