### ISSUE TITLE
Mark a DM channel as read when replying

### ISSUE THREAD

**Issue by harimp** [erroneousboat/slack-term#74]
First off, I love the app. I pretty much live in terminal for work, and it's great to have a slack client that works really well.

I've been noticing that if you're in a DM channel and get a new message, then the channel isn't marked "read" until you get out of the DM channel and back in (ie [ j ] [ k ] in normal mode). It's a minor inconvenience, but it would be nice if on replying a DM message sets the channel as read.

**Comment by erroneousboat** [comment]
Hi, thank you, and I'm glad that you like it! I'm guessing this mainly happens when you selected channel `x` and receive a notification on said channel. The reason I've done it like this is because I personally use slack-term inside tmux. 

When switching between windows in tmux the only indication I have is an audible one (terminal bell) when a message is received in slack-term. When the sound is off, I won't have a way of knowing that a new message has been received on channel `x`. So when I return to slack-term I will see the notification in front of channel `x`.

If I implement it as you suggested I won't be able to see the notification in channel `x`, because `x` was the selected channel and changed I changed windows in tmux. So I would potentially miss the message.
